# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: dolphinnext
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - r-base=4.1.2
 